"""Added measure field to Item model

Revision ID: 9fe0cba069c3
Revises: cbc9cadb0f50
Create Date: 2025-12-01 19:42:33.808601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9fe0cba069c3'
down_revision: Union[str, Sequence[str], None] = 'cbc9cadb0f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items',
                  sa.Column('measure', sa.String(length=256), nullable=False,
                            server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'measure')
    # ### end Alembic commands ###
