"""Added unique constraint

Revision ID: cbc9cadb0f50
Revises: 3ffe2531fbb7
Create Date: 2025-11-29 19:24:20.805003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc9cadb0f50'
down_revision: Union[str, Sequence[str], None] = '3ffe2531fbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_order_item_uc', 'ordered_items', ['order_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_item_uc', 'ordered_items', type_='unique')
    # ### end Alembic commands ###
